<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/banner_IA.png"  width="1000px" height="250px">



# <center> **AVANCE PROYECTO FINAL:** </center>
# <center> **Sistema de Monitoreo de Acciones Peligrosas en el Conductor** </center>
# <center> **Iván Augusto Camargo López - 2230033** </center>
# <center> **Santiago Torres - 2202024** </center>



## **Índice**
1. **Preprocesamiento: Repaso y Compilación del Dataset**
2. **Aplicación: Algoritmos de Machine Learning**
3. **Aplicación: Mejorando Algoritmos de Machine Learning**
4. **Más allá: Implementación de Técnicas para la Mejora del Modelo**

# 1. **Preprocesamiento: Repaso y Compilación del Dataset**

* Recordando, para este momento se han extraído las posturas de **16** sujetos distintos, Procedentes de la utilización de **VitPose** y **MediaPipe** para la identificación de **landmarks**

* En primer lugar, vamos a juntar los dataframes obtenidos para cada vídeo en un único dataframe, contatenándolos a lo largo del eje 0:

In [ ]:
#@title Juntar partes del Dataset Final
import pandas as pd
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive')

# Definir rutas de los archivos CSV en Google Drive
csv_paths = [
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_1",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_2",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_2",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_3",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_4",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_5",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_6",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_7",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_8",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_9",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_10_1",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_10_2",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_11",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_12",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_13",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_14",
    "/content/drive/MyDrive/frames_definitivos/DMD_Dataset_Final_15",
]

# Leer los archivos CSV como DataFrames
dfs = [pd.read_csv(path) for path in csv_paths]

# Unir los DataFrames en uno solo (por filas, manteniendo las mismas columnas)
df_final = pd.concat(dfs, ignore_index=False)

#  Guardar el DataFrame combinado en Google Drive
output_path = "/content/drive/MyDrive/DMD_Dataset_Project.csv"
df_final.to_csv(output_path)

#  Confirmación
print(f"Dataset combinado guardado en: {output_path}")

# Mostrar las primeras filas del DataFrame final
df_final.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]
<ipython-input-41-6f2796257e2e>:30: DtypeWarning: Columns (1451) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(path) for path in csv_paths]

Dataset combinado guardado en: /content/drive/MyDrive/DMD_Dataset_Project.csv

,index,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,lmk_2_z,...,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning,occlusion
0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,-0.024851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,-0.024461,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,-0.023093,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,-0.023609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,-0.023432,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN

In [ ]:
#@title Cargar el Dataset Final (sin procesar)

import pandas as pd
from google.colab import drive
import numpy as np

# Montar Google Drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/DMD_Dataset_Project.csv"

df_final = pd.read_csv(path)
df_final.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<ipython-input-2-4ce58f09b131>:12: DtypeWarning: Columns (1,1452) have mixed types. Specify dtype option on import or set low_memory=False.
  df_final = pd.read_csv(path)

,Unnamed: 0,index,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,...,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning,occlusion
0,0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
1,1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
2,2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
3,3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
4,4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN

In [ ]:
df_final.shape

(92491, 1454)

In [ ]:
#@title Modificaciones al Dataset final

df_final = df_final.reset_index().rename(columns={"index": "indice_video"})

In [ ]:
df_final.head()

,indice_video,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,lmk_2_z,...,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning,occlusion
0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,-0.024851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,-0.024461,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,-0.023093,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,-0.023609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN
4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,-0.023432,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eyes_state/open,NaN,NaN

In [ ]:
df_final = df_final.drop('Unnamed: 0',axis = 1)

In [ ]:
df_final = df_final.drop('level_0',axis = 1)

In [ ]:
valores_distintos = df_final["occlusion"].unique().tolist()
valores_distintos

[nan]

In [ ]:
#@title Mapeado de las características

blinks_map_table = {
    'Etiqueta original': ['NaN', 'blinks/blinking'],
    'Valor numérico': [0, 1]
}

df_map = pd.DataFrame(blinks_map_table)
df_map

  Etiqueta original  Valor numérico
0               NaN               0
1   blinks/blinking               1

In [ ]:
eyes_state_map_table = {
    'Etiqueta original': ['NaN', 'eyes_state/open', 'eyes_state/close','eyes_state/opening', 'eyes_state/closing', 'eyes_state/undefined'],
    'Valor numérico': [0, 1, 2,3,4,5]
}

df_map = pd.DataFrame(eyes_state_map_table)
df_map

      Etiqueta original  Valor numérico
0                   NaN               0
1       eyes_state/open               1
2      eyes_state/close               2
3    eyes_state/opening               3
4    eyes_state/closing               4
5  eyes_state/undefined               5

In [ ]:
yawning_map_table = {
    'Etiqueta original': ['NaN', 'yawning/Yawning without hand', 'yawning/Yawning with hand'],
    'Valor numérico': [0, 1, 2]
}

df_map = pd.DataFrame(yawning_map_table)
df_map

              Etiqueta original  Valor numérico
0                           NaN               0
1  yawning/Yawning without hand               1
2     yawning/Yawning with hand               2

In [ ]:
#@title Modificando las etiquetas

blinks_map = {
np.nan: 0,
'blinks/blinking': 1,
}

eyes_state_map = {
np.nan: 0,
'eyes_state/open': 1,
'eyes_state/close': 2,
'eyes_state/opening': 3,
'eyes_state/closing': 4,
'eyes_state/undefined': 5
}

yawning_map = {
np.nan: 0,
'yawning/Yawning without hand': 1,
'yawning/Yawning with hand': 2
}

# Aplicamos el mapeo respetando los NaN
df_final['blinks'] = df_final['blinks'].map(lambda x: blinks_map[np.nan] if pd.isna(x) else blinks_map.get(x))
df_final['eyes_state'] = df_final['eyes_state'].map(lambda x: eyes_state_map[np.nan] if pd.isna(x) else eyes_state_map.get(x))
df_final['yawning'] = df_final['yawning'].map(lambda x: yawning_map[np.nan] if pd.isna(x) else yawning_map.get(x))

#Como la columna Occlusion solo tiene NaN, podemos eliminarla:

df_final = df_final.drop('occlusion',axis = 1)

In [ ]:
df_final.head()

,indice_video,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,lmk_2_z,...,lmk_hand_125_y,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning
0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,-0.024851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0
1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,-0.024461,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0
2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,-0.023093,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0
3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,-0.023609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0
4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,-0.023432,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0

In [ ]:
#@title Reemplazando los NaN restantes por 0

df_final = df_final.fillna(0)

In [ ]:
#@title Guardamos el dataset con las modificaciones

#  Guardar el DataFrame combinado en Google Drive
output_path = "/content/drive/MyDrive/DMD_Dataset_Project_Processed.csv"
df_final.to_csv(output_path)

#  Confirmación
print(f"Dataset combinado guardado en: {output_path}")

Dataset combinado guardado en: /content/drive/MyDrive/DMD_Dataset_Project_Processed.csv

# 2. **Aplicación: Algoritmos de Machine Learning**

In [ ]:
#@title Cargar el Dataset Final (ya procesado)

import pandas as pd
from google.colab import drive
import numpy as np

# Montar Google Drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/DMD_Dataset_Project_Processed.csv"

df = pd.read_csv(path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<ipython-input-1-224398f1916b>:12: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,Unnamed: 0,indice_video,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,...,lmk_hand_125_y,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning
0,0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
2,2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
3,3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
4,4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0

In [ ]:
df = df.drop('Unnamed: 0', axis = 1)

In [ ]:
df.head()

,indice_video,lmk_0_x,lmk_0_y,lmk_0_z,lmk_1_x,lmk_1_y,lmk_1_z,lmk_2_x,lmk_2_y,lmk_2_z,...,lmk_hand_125_y,lmk_hand_127_x,lmk_hand_127_y,lmk_hand_129_x,lmk_hand_129_y,lmk_hand_131_x,lmk_hand_131_y,blinks,eyes_state,yawning
0,1.1,0.466321,0.664493,-0.030458,0.464244,0.610660,-0.037667,0.463933,0.632606,-0.024851,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,1.2,0.466716,0.667113,-0.030338,0.464099,0.612234,-0.037929,0.464176,0.634038,-0.024461,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
2,1.3,0.446711,0.726543,-0.025353,0.444824,0.676071,-0.040332,0.445900,0.693371,-0.023093,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
3,1.4,0.472639,0.689401,-0.027664,0.472933,0.639516,-0.037768,0.472006,0.659946,-0.023609,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
4,1.5,0.472732,0.689614,-0.027691,0.473167,0.639140,-0.037587,0.472129,0.659548,-0.023432,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

# Preparación de datos
X = df.drop(["yawning", "indice_video"], axis=1)
y = df['yawning']

# Entrenamiento del modelo
est = DecisionTreeClassifier(max_depth=10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=21)
est.fit(X_train, y_train)

# Obtener importancias
importances = est.feature_importances_
feature_names = X.columns

# Crear DataFrame de importancias
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Mostrar las 30 features más importantes
top_30 = importance_df.head(100)
print("Top 30 features más importantes:")
print(top_30)

Top 30 features más importantes:
        Feature  Importance
732   lmk_244_x    0.030922
516   lmk_172_x    0.028511
396   lmk_132_x    0.026514
1037  lmk_345_z    0.025941
304   lmk_101_y    0.025341
1095  lmk_365_x    0.025027
408   lmk_136_x    0.022558
419   lmk_139_z    0.017768
1372  lmk_457_y    0.017724
580   lmk_193_y    0.016156
174    lmk_58_x    0.015584
1084  lmk_361_y    0.015218
1064  lmk_354_z    0.015080
617   lmk_205_z    0.014974
157    lmk_52_y    0.013869
143    lmk_47_z    0.013466
1286  lmk_428_z    0.013310
707   lmk_235_z    0.012899
1199  lmk_399_z    0.012886
486   lmk_162_x    0.012795
11      lmk_3_z    0.012568
1189  lmk_396_y    0.012119
944   lmk_314_z    0.012109
1070  lmk_356_z    0.011921
611   lmk_203_z    0.011903
293    lmk_97_z    0.011844
1002  lmk_334_x    0.011303
1099  lmk_366_y    0.011056
819   lmk_273_x    0.010925
710   lmk_236_z    0.010633

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import re

# Preparación de datos
X = df.drop(["yawning", "indice_video"], axis=1)
y = df['yawning']

# Entrenamiento del modelo
est = DecisionTreeClassifier(max_depth=10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=21)
est.fit(X_train, y_train)

# Obtener importancias
importances = est.feature_importances_
feature_names = X.columns

# Crear DataFrame de importancias
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Mostrar las 100 features más importantes
top_100 = importance_df.head(20)
print("Top 100 features más importantes:")
print(top_100)

# Extraer números de landmarks de las features top
landmarks_importantes = set()

for feature in top_100['Feature']:
    match = re.match(r'lmk_(\d+)_', feature)
    if match:
        landmarks_importantes.add(int(match.group(1)))

# Convertir a lista ordenada
landmarks_importantes = sorted(list(landmarks_importantes))

print("\nLandmarks más importantes:")
print(landmarks_importantes)

Top 100 features más importantes:
        Feature  Importance
732   lmk_244_x    0.030933
516   lmk_172_x    0.028522
396   lmk_132_x    0.026523
1037  lmk_345_z    0.025951
304   lmk_101_y    0.025350
1095  lmk_365_x    0.025036
408   lmk_136_x    0.022566
1372  lmk_457_y    0.019002
1084  lmk_361_y    0.018283
419   lmk_139_z    0.017775
143    lmk_47_z    0.016253
580   lmk_193_y    0.016162
174    lmk_58_x    0.015590
1064  lmk_354_z    0.015086
443   lmk_147_z    0.014979
157    lmk_52_y    0.013874
1286  lmk_428_z    0.013314
293    lmk_97_z    0.012992
707   lmk_235_z    0.012904
1199  lmk_399_z    0.012891

Landmarks más importantes:
[47, 52, 58, 97, 101, 132, 136, 139, 147, 172, 193, 235, 244, 345, 354, 361, 365, 399, 428, 457]

In [ ]:
del importances
del feature_names
del X
del y

import gc
gc.collect()

0

* Para nuestro caso de estudio, se cuenta con 3 etiquetas: 'eyes_state', 'blinks', y 'yawning'.

* Hay varias maneras de abordar este problema, pero hay que tener un factor fundamental en cuenta para evitar el **data leakage**: a la hora de probar el modelo en la vida real, no se cuenta con ninguna de estas etiquetas, y, de momento, solo podemos predecir una de ellas a la vez.

* Por tanto, no podemos entrenar el modelo para predecir, por ejemplo, 'yawning' teniendo en cuenta todos los demás features, pues esto incluiría 'eyes_state' y 'blinking'

* Dicho esto, se puede proceder de distintas formas:

* A) Crear 3 modelos diferentes, uno que prediga "blinks", otro que prediga "eyes_state" y otro que prediga "yawning", los 3 por separado. Solo se usan el resto de features para entrenar el modelo, teniendo en cuenta que en la vida real solo puedo extraer coordenadas, no etiquetas.

* B) Crear modelos en cascada. Es decir, un modelo que prediga "blinks" solo con coordenadas, otro que prediga "eyes_state" con "blinks" y las coordenadas, y otro que prediga "yawning" con las coordenadas, "blinks" y "eyes_state".  (Por ejemplo)

* C) Modelos en árbol. Un modelo predice "blinks" a partir de coordenadas, otro "eyes_state" a partir de coordenadas, y otro "yawning" con base en "eyes_state", "blinks" y las coordenadas (Por ejemplo)

* Ahora, como vamos a empezar por evaluar los modelos para obtener cada una de las etiquetas por separado, asumiendo que no contamos con ellas para predecirse entre sí.

In [ ]:
#@title Importaciones

from sklearn.model_selection import cross_validate, KFold
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
from IPython.display import display
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

import tensorflow as tf
from tensorflow import keras
!pip install scikeras
!pip install --upgrade scikit-learn scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.15.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.13.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: scikeras in /usr/local/lib/python3.11/dist-packages (0.13.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.15.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.13.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)

# **Naive Gaussian Bayes**

In [ ]:
#@title Utilizando un Kfold de 10

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = GaussianNB()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(10, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(10, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(10, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

,blinks,eyes_state,yawning
train_Accuracy,0.639 (+/- 0.00062),0.079 (+/- 0.02351),0.130 (+/- 0.00127)
test_Accuracy,0.639 (+/- 0.00524),0.079 (+/- 0.02433),0.130 (+/- 0.00392)
train_Precision,0.570 (+/- 0.00086),0.476 (+/- 0.00355),0.829 (+/- 0.00052)
test_Precision,0.569 (+/- 0.00760),0.474 (+/- 0.01469),0.829 (+/- 0.00833)
train_Recall,0.639 (+/- 0.00062),0.079 (+/- 0.02351),0.130 (+/- 0.00127)
test_Recall,0.639 (+/- 0.00524),0.079 (+/- 0.02433),0.130 (+/- 0.00392)
train_F1_Score,0.556 (+/- 0.00083),0.129 (+/- 0.03460),0.138 (+/- 0.00211)
test_F1_Score,0.556 (+/- 0.00710),0.129 (+/- 0.03576),0.138 (+/- 0.00492)
train_Cohen_Kappa,0.024 (+/- 0.00073),0.003 (+/- 0.00105),0.012 (+/- 0.00016)
test_Cohen_Kappa,0.023 (+/- 0.00663),0.003 (+/- 0.00248),0.012 (+/- 0.00185)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = GaussianNB()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.638      0.089   0.131
test_Accuracy      0.641      0.088   0.131
train_Precision    0.568      0.481   0.831
test_Precision     0.576      0.482   0.827
train_Recall       0.638      0.089   0.131
test_Recall        0.641      0.088   0.131
train_F1_Score     0.555      0.146   0.140
test_F1_Score      0.560      0.144   0.141
train_Cohen_Kappa  0.022      0.004   0.012
test_Cohen_Kappa   0.030      0.002   0.011

# **Decision Tree Classifier**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = DecisionTreeClassifier()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

,blinks,eyes_state,yawning
train_Accuracy,0.984 (+/- 0.00014),0.984 (+/- 0.00022),0.997 (+/- 0.00010)
test_Accuracy,0.774 (+/- 0.00176),0.704 (+/- 0.00174),0.934 (+/- 0.00167)
train_Precision,0.984 (+/- 0.00013),0.984 (+/- 0.00021),0.997 (+/- 0.00010)
test_Precision,0.773 (+/- 0.00171),0.704 (+/- 0.00273),0.933 (+/- 0.00187)
train_Recall,0.984 (+/- 0.00014),0.984 (+/- 0.00022),0.997 (+/- 0.00010)
test_Recall,0.774 (+/- 0.00176),0.704 (+/- 0.00174),0.934 (+/- 0.00167)
train_F1_Score,0.984 (+/- 0.00014),0.983 (+/- 0.00022),0.997 (+/- 0.00010)
test_F1_Score,0.773 (+/- 0.00171),0.704 (+/- 0.00209),0.933 (+/- 0.00177)
train_Cohen_Kappa,0.964 (+/- 0.00033),0.969 (+/- 0.00043),0.985 (+/- 0.00041)
test_Cohen_Kappa,0.496 (+/- 0.00696),0.442 (+/- 0.00424),0.703 (+/- 0.00992)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = DecisionTreeClassifier()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.772      0.709   0.940
train_Precision    0.984      0.984   0.997
test_Precision     0.771      0.709   0.940
train_Recall       0.984      0.984   0.997
test_Recall        0.772      0.709   0.940
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.772      0.709   0.940
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.493      0.451   0.730

# **Random Forest Classifier**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = RandomForestClassifier()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

,blinks,eyes_state,yawning
train_Accuracy,0.984 (+/- 0.00024),0.984 (+/- 0.00016),0.997 (+/- 0.00011)
test_Accuracy,0.859 (+/- 0.00244),0.807 (+/- 0.00241),0.966 (+/- 0.00156)
train_Precision,0.984 (+/- 0.00023),0.984 (+/- 0.00016),0.997 (+/- 0.00011)
test_Precision,0.859 (+/- 0.00239),0.799 (+/- 0.00298),0.966 (+/- 0.00155)
train_Recall,0.984 (+/- 0.00024),0.984 (+/- 0.00016),0.997 (+/- 0.00011)
test_Recall,0.859 (+/- 0.00244),0.807 (+/- 0.00241),0.966 (+/- 0.00156)
train_F1_Score,0.984 (+/- 0.00024),0.983 (+/- 0.00017),0.997 (+/- 0.00011)
test_F1_Score,0.855 (+/- 0.00260),0.787 (+/- 0.00231),0.964 (+/- 0.00175)
train_Cohen_Kappa,0.964 (+/- 0.00055),0.969 (+/- 0.00031),0.985 (+/- 0.00051)
test_Cohen_Kappa,0.673 (+/- 0.00522),0.586 (+/- 0.00540),0.830 (+/- 0.00938)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.861      0.806   0.969
train_Precision    0.984      0.984   0.997
test_Precision     0.862      0.799   0.969
train_Recall       0.984      0.984   0.997
test_Recall        0.861      0.806   0.969
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.857      0.785   0.967
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.679      0.583   0.843

# **Support Vector Machine**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = SVC()


# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/svm/_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

,blinks,eyes_state,yawning
train_Accuracy,0.496 (+/- 0.08355),0.360 (+/- 0.05565),0.480 (+/- 0.19594)
test_Accuracy,0.499 (+/- 0.08217),0.360 (+/- 0.05678),0.479 (+/- 0.19554)
train_Precision,0.541 (+/- 0.02227),0.420 (+/- 0.00855),0.776 (+/- 0.01844)
test_Precision,0.545 (+/- 0.02465),0.420 (+/- 0.01087),0.775 (+/- 0.01806)
train_Recall,0.496 (+/- 0.08355),0.360 (+/- 0.05565),0.480 (+/- 0.19594)
test_Recall,0.499 (+/- 0.08217),0.360 (+/- 0.05678),0.479 (+/- 0.19554)
train_F1_Score,0.452 (+/- 0.10491),0.382 (+/- 0.03563),0.537 (+/- 0.22686)
test_F1_Score,0.455 (+/- 0.10459),0.381 (+/- 0.03709),0.536 (+/- 0.22667)
train_Cohen_Kappa,-0.022 (+/- 0.03145),-0.024 (+/- 0.00899),-0.012 (+/- 0.00754)
test_Cohen_Kappa,-0.017 (+/- 0.03309),-0.024 (+/- 0.00948),-0.013 (+/- 0.00729)

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = SVC()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = SVC()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.657      0.652   0.875
test_Accuracy      0.658      0.653   0.878
train_Precision    0.645      0.426   0.766
test_Precision     0.662      0.426   0.771
train_Recall       0.657      0.652   0.875
test_Recall        0.658      0.653   0.878
train_F1_Score     0.531      0.515   0.817
test_F1_Score      0.532      0.515   0.821
train_Cohen_Kappa  0.017      0.000   0.000
test_Cohen_Kappa   0.020      0.000   0.000

# **Logistic Regression**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = LogisticRegression(max_iter=1000)

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,blinks,eyes_state,yawning
train_Accuracy,0.658 (+/- 0.00078),0.652 (+/- 0.00082),0.876 (+/- 0.00045)
test_Accuracy,0.657 (+/- 0.00315),0.652 (+/- 0.00259),0.876 (+/- 0.00173)
train_Precision,0.643 (+/- 0.00393),0.504 (+/- 0.02259),0.817 (+/- 0.00645)
test_Precision,0.631 (+/- 0.00910),0.479 (+/- 0.02091),0.815 (+/- 0.00856)
train_Recall,0.658 (+/- 0.00078),0.652 (+/- 0.00082),0.876 (+/- 0.00045)
test_Recall,0.657 (+/- 0.00315),0.652 (+/- 0.00259),0.876 (+/- 0.00173)
train_F1_Score,0.534 (+/- 0.00100),0.516 (+/- 0.00115),0.818 (+/- 0.00067)
test_F1_Score,0.532 (+/- 0.00412),0.516 (+/- 0.00316),0.818 (+/- 0.00256)
train_Cohen_Kappa,0.020 (+/- 0.00110),0.002 (+/- 0.00089),0.002 (+/- 0.00028)
test_Cohen_Kappa,0.018 (+/- 0.00256),0.002 (+/- 0.00054),0.002 (+/- 0.00059)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = LogisticRegression(max_iter=1000)

est.fit(X_train,y_train)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.657      0.652   0.875
test_Accuracy      0.658      0.652   0.878
train_Precision    0.637      0.475   0.811
test_Precision     0.646      0.481   0.815
train_Recall       0.657      0.652   0.875
test_Recall        0.658      0.652   0.878
train_F1_Score     0.534      0.516   0.818
test_F1_Score      0.535      0.516   0.822
train_Cohen_Kappa  0.020      0.001   0.002
test_Cohen_Kappa   0.023      0.001   0.002

# **Kneighbors Classifier**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = KNeighborsClassifier()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

,blinks,eyes_state,yawning
train_Accuracy,0.901 (+/- 0.00063),0.861 (+/- 0.00074),0.980 (+/- 0.00024)
test_Accuracy,0.846 (+/- 0.00331),0.785 (+/- 0.00178),0.968 (+/- 0.00129)
train_Precision,0.901 (+/- 0.00062),0.857 (+/- 0.00073),0.979 (+/- 0.00025)
test_Precision,0.844 (+/- 0.00341),0.767 (+/- 0.00229),0.968 (+/- 0.00132)
train_Recall,0.901 (+/- 0.00063),0.861 (+/- 0.00074),0.980 (+/- 0.00024)
test_Recall,0.846 (+/- 0.00331),0.785 (+/- 0.00178),0.968 (+/- 0.00129)
train_F1_Score,0.900 (+/- 0.00067),0.854 (+/- 0.00076),0.979 (+/- 0.00025)
test_F1_Score,0.844 (+/- 0.00336),0.769 (+/- 0.00225),0.968 (+/- 0.00127)
train_Cohen_Kappa,0.778 (+/- 0.00162),0.722 (+/- 0.00139),0.907 (+/- 0.00117)
test_Cohen_Kappa,0.652 (+/- 0.00799),0.562 (+/- 0.00512),0.854 (+/- 0.00553)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = KNeighborsClassifier()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.903      0.863   0.979
test_Accuracy      0.843      0.789   0.969
train_Precision    0.903      0.858   0.979
test_Precision     0.841      0.772   0.968
train_Recall       0.903      0.863   0.979
test_Recall        0.843      0.789   0.969
train_F1_Score     0.902      0.855   0.979
test_F1_Score      0.842      0.773   0.968
train_Cohen_Kappa  0.781      0.724   0.906
test_Cohen_Kappa   0.647      0.570   0.854

# **Linear Discriminant Analysis**

In [ ]:
#@title Utilizando un Kfold de 5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

# Definimos los "scorers"
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score, average='weighted', zero_division=0),
    'recall': make_scorer(recall_score, average='weighted', zero_division=0),
    'f1': make_scorer(f1_score, average='weighted', zero_division=0),
    'cohen_kappa': make_scorer(cohen_kappa_score)
}

#Modelo

est = LinearDiscriminantAnalysis()

# Validación cruzada
resultados_blinks = cross_validate(est, X, y1, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_eyes_state = cross_validate(est, X, y2, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)
resultados_yawning = cross_validate(est, X, y3, cv=KFold(5, shuffle=True), scoring=scoring, return_train_score=True)

metricas = {
    'blinks': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_accuracy']), np.std(resultados_blinks['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_accuracy']), np.std(resultados_blinks['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_precision']), np.std(resultados_blinks['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_precision']), np.std(resultados_blinks['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_recall']), np.std(resultados_blinks['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_recall']), np.std(resultados_blinks['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_f1']), np.std(resultados_blinks['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_f1']), np.std(resultados_blinks['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['train_cohen_kappa']), np.std(resultados_blinks['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_blinks['test_cohen_kappa']), np.std(resultados_blinks['test_cohen_kappa'])),
    },
    'eyes_state': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_accuracy']), np.std(resultados_eyes_state['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_accuracy']), np.std(resultados_eyes_state['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_precision']), np.std(resultados_eyes_state['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_precision']), np.std(resultados_eyes_state['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_recall']), np.std(resultados_eyes_state['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_recall']), np.std(resultados_eyes_state['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_f1']), np.std(resultados_eyes_state['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_f1']), np.std(resultados_eyes_state['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['train_cohen_kappa']), np.std(resultados_eyes_state['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_eyes_state['test_cohen_kappa']), np.std(resultados_eyes_state['test_cohen_kappa'])),
    },
    'yawning': {
        'train_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_accuracy']), np.std(resultados_yawning['train_accuracy'])),
        'test_Accuracy': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_accuracy']), np.std(resultados_yawning['test_accuracy'])),
        'train_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_precision']), np.std(resultados_yawning['train_precision'])),
        'test_Precision': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_precision']), np.std(resultados_yawning['test_precision'])),
        'train_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_recall']), np.std(resultados_yawning['train_recall'])),
        'test_Recall': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_recall']), np.std(resultados_yawning['test_recall'])),
        'train_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_f1']), np.std(resultados_yawning['train_f1'])),
        'test_F1_Score': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_f1']), np.std(resultados_yawning['test_f1'])),
        'train_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['train_cohen_kappa']), np.std(resultados_yawning['train_cohen_kappa'])),
        'test_Cohen_Kappa': "%.3f (+/- %.5f)"%(np.mean(resultados_yawning['test_cohen_kappa']), np.std(resultados_yawning['test_cohen_kappa'])),
    }
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

,blinks,eyes_state,yawning
train_Accuracy,0.663 (+/- 0.00055),0.651 (+/- 0.00105),0.880 (+/- 0.00039)
test_Accuracy,0.659 (+/- 0.00101),0.649 (+/- 0.00298),0.879 (+/- 0.00212)
train_Precision,0.634 (+/- 0.00172),0.593 (+/- 0.00138),0.850 (+/- 0.00068)
test_Precision,0.622 (+/- 0.00278),0.568 (+/- 0.00540),0.847 (+/- 0.00331)
train_Recall,0.663 (+/- 0.00055),0.651 (+/- 0.00105),0.880 (+/- 0.00039)
test_Recall,0.659 (+/- 0.00101),0.649 (+/- 0.00298),0.879 (+/- 0.00212)
train_F1_Score,0.579 (+/- 0.00081),0.536 (+/- 0.00130),0.853 (+/- 0.00055)
test_F1_Score,0.574 (+/- 0.00108),0.533 (+/- 0.00446),0.850 (+/- 0.00247)
train_Cohen_Kappa,0.080 (+/- 0.00186),0.052 (+/- 0.00074),0.241 (+/- 0.00334)
test_Cohen_Kappa,0.069 (+/- 0.00292),0.045 (+/- 0.00318),0.229 (+/- 0.00961)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = LinearDiscriminantAnalysis()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.662      0.650   0.880
test_Accuracy      0.660      0.650   0.882
train_Precision    0.631      0.589   0.850
test_Precision     0.625      0.588   0.850
train_Recall       0.662      0.650   0.880
test_Recall        0.660      0.650   0.882
train_F1_Score     0.578      0.536   0.852
test_F1_Score      0.574      0.535   0.853
train_Cohen_Kappa  0.077      0.052   0.243
test_Cohen_Kappa   0.071      0.052   0.227

# **Deep Learning**

In [ ]:
#@title Utilizando un Kfold de 5

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
import pandas as pd
import numpy as np

# Preparar X y los targets
X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
targets = {
    'blinks': df['blinks'],
    'eyes_state': df['eyes_state'],
    'yawning': df['yawning']
}

# Función para construir el modelo
def construir_modelo(n_classes):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dropout(0.3))
    model.add(Dense(32, activation='relu'))

    if n_classes == 2:
        model.add(Dense(1, activation='sigmoid'))
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    else:
        model.add(Dense(n_classes, activation='softmax'))
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

# KFold manual
kf = KFold(n_splits=5, shuffle=True, random_state=42)
metricas = {}

# Loop para las tres etiquetas
for nombre, y in targets.items():
    n_classes = y.nunique()
    metricas_fold = []

    for train_idx, test_idx in kf.split(X):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        est = KerasClassifier(
            model=lambda: construir_modelo(n_classes),
            epochs=20,
            batch_size=32,
            verbose=0
        )

        est.fit(X_train, y_train)
        y_pred_train = est.predict(X_train)
        y_pred_test = est.predict(X_test)

        metricas_fold.append({
            'train_Accuracy': accuracy_score(y_train, y_pred_train),
            'test_Accuracy': accuracy_score(y_test, y_pred_test),
            'train_Precision': precision_score(y_train, y_pred_train, average='weighted', zero_division=0),
            'test_Precision': precision_score(y_test, y_pred_test, average='weighted', zero_division=0),
            'train_Recall': recall_score(y_train, y_pred_train, average='weighted', zero_division=0),
            'test_Recall': recall_score(y_test, y_pred_test, average='weighted', zero_division=0),
            'train_F1_Score': f1_score(y_train, y_pred_train, average='weighted', zero_division=0),
            'test_F1_Score': f1_score(y_test, y_pred_test, average='weighted', zero_division=0),
            'train_Cohen_Kappa': cohen_kappa_score(y_train, y_pred_train),
            'test_Cohen_Kappa': cohen_kappa_score(y_test, y_pred_test)
        })

    # Promediar métricas por etiqueta
    df_temp = pd.DataFrame(metricas_fold)
    metricas[nombre] = {
        col: "%.3f (+/- %.5f)" % (df_temp[col].mean(), df_temp[col].std())
        for col in df_temp.columns
    }

# Mostrar como DataFrame
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

,blinks,eyes_state,yawning
train_Accuracy,0.657 (+/- 0.00070),0.654 (+/- 0.00076),0.876 (+/- 0.00057)
test_Accuracy,0.657 (+/- 0.00275),0.653 (+/- 0.00319),0.876 (+/- 0.00225)
train_Precision,0.672 (+/- 0.02208),0.640 (+/- 0.00744),0.826 (+/- 0.00171)
test_Precision,0.647 (+/- 0.00869),0.574 (+/- 0.01420),0.824 (+/- 0.00431)
train_Recall,0.657 (+/- 0.00070),0.654 (+/- 0.00076),0.876 (+/- 0.00057)
test_Recall,0.657 (+/- 0.00275),0.653 (+/- 0.00319),0.876 (+/- 0.00225)
train_F1_Score,0.528 (+/- 0.00206),0.520 (+/- 0.00135),0.819 (+/- 0.00082)
test_F1_Score,0.527 (+/- 0.00336),0.518 (+/- 0.00384),0.819 (+/- 0.00333)
train_Cohen_Kappa,0.014 (+/- 0.00168),0.010 (+/- 0.00176),0.007 (+/- 0.00058)
test_Cohen_Kappa,0.012 (+/- 0.00301),0.006 (+/- 0.00167),0.006 (+/- 0.00140)

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
import pandas as pd
import numpy as np

# Features y variables objetivo
X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
targets = {
    'blinks': df['blinks'],
    'eyes_state': df['eyes_state'],
    'yawning': df['yawning']
}

# Función para construir modelo
def construir_modelo(n_classes):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dropout(0.3))
    model.add(Dense(32, activation='relu'))

    if n_classes == 2:
        model.add(Dense(1, activation='sigmoid'))
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    else:
        model.add(Dense(n_classes, activation='softmax'))
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

# Métricas
metricas = {}

# Loop por cada variable target
for nombre, y in targets.items():
    n_classes = y.nunique()

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

    # KerasClassifier wrapper
    est = KerasClassifier(
        model=lambda: construir_modelo(n_classes),
        epochs=20,
        batch_size=32,
        verbose=0
    )

    est.fit(X_train, y_train)

    y_pred_train = est.predict(X_train)
    y_pred_test = est.predict(X_test)

    metricas[nombre] = {
        'train_Accuracy': "%.3f"%(accuracy_score(y_train, y_pred_train)),
        'test_Accuracy': "%.3f"%(accuracy_score(y_test, y_pred_test)),
        'train_Precision': "%.3f"%(precision_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Precision': "%.3f"%(precision_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Recall': "%.3f"%(recall_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Recall': "%.3f"%(recall_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_F1_Score': "%.3f"%(f1_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_F1_Score': "%.3f"%(f1_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train, y_pred_train)),
        'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test, y_pred_test)),
    }

# Mostrar tabla
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

                  blinks eyes_state yawning
train_Accuracy     0.657      0.654   0.876
test_Accuracy      0.656      0.653   0.879
train_Precision    0.702      0.654   0.822
test_Precision     0.669      0.573   0.823
train_Recall       0.657      0.654   0.876
test_Recall        0.656      0.653   0.879
train_F1_Score     0.526      0.520   0.818
test_F1_Score      0.524      0.518   0.823
train_Cohen_Kappa  0.012      0.010   0.007
test_Cohen_Kappa   0.008      0.006   0.010

# 3. **Aplicación: Mejorando Algoritmos de Machine Learning**

# **Decision Tree Classifier**

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = DecisionTreeClassifier(
    max_depth=100,
    min_samples_split=100,
    min_samples_leaf=50,
    max_features='log2',
    criterion='gini',
    class_weight='balanced'
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.772      0.709   0.940
train_Precision    0.984      0.984   0.997
test_Precision     0.771      0.709   0.940
train_Recall       0.984      0.984   0.997
test_Recall        0.772      0.709   0.940
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.772      0.709   0.940
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.493      0.451   0.730

# **RandomForestClassifier**

In [ ]:
#@title RandomForest1

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=200,
    max_depth=30,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features='sqrt',
    criterion='gini',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    oob_score=True
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.977      0.955   0.997
test_Accuracy      0.856      0.781   0.972
train_Precision    0.979      0.997   0.997
test_Precision     0.855      0.804   0.972
train_Recall       0.977      0.955   0.997
test_Recall        0.856      0.781   0.972
train_F1_Score     0.978      0.974   0.997
test_F1_Score      0.855      0.783   0.971
train_Cohen_Kappa  0.951      0.918   0.988
test_Cohen_Kappa   0.679      0.568   0.863

In [ ]:
#@title RandomForest2

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=150,
    max_depth=25,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features='sqrt',
    criterion='gini',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    oob_score=True
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.965      0.952   0.995
test_Accuracy      0.842      0.774   0.970
train_Precision    0.968      0.994   0.995
test_Precision     0.843      0.796   0.969
train_Recall       0.965      0.952   0.995
test_Recall        0.842      0.774   0.970
train_F1_Score     0.966      0.972   0.995
test_F1_Score      0.842      0.779   0.968
train_Cohen_Kappa  0.925      0.913   0.980
test_Cohen_Kappa   0.653      0.562   0.852

In [ ]:
#@title RandomForest3

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features='sqrt',
    criterion='gini',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    oob_score=True
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.971      0.955   0.997
test_Accuracy      0.851      0.781   0.970
train_Precision    0.973      0.997   0.997
test_Precision     0.850      0.804   0.970
train_Recall       0.971      0.955   0.997
test_Recall        0.851      0.781   0.970
train_F1_Score     0.971      0.974   0.997
test_F1_Score      0.850      0.782   0.969
train_Cohen_Kappa  0.937      0.919   0.985
test_Cohen_Kappa   0.667      0.564   0.852

In [ ]:
#@title RandomForest4

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=200
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.863      0.810   0.970
train_Precision    0.984      0.984   0.997
test_Precision     0.863      0.803   0.970
train_Recall       0.984      0.984   0.997
test_Recall        0.863      0.810   0.970
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.859      0.789   0.968
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.682      0.591   0.847

In [ ]:
#@title RandomForest5

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=500
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.864      0.810   0.969
train_Precision    0.984      0.984   0.997
test_Precision     0.864      0.803   0.969
train_Recall       0.984      0.984   0.997
test_Recall        0.864      0.810   0.969
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.860      0.789   0.967
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.685      0.591   0.845

# **Support Vector Machine**

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = SVC(
    kernel='linear',
    C=2.0,
    gamma='scale',
    class_weight='balanced',
    random_state=42,
    max_iter=200,
    tol=1e-3
    )

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.657      0.652   0.875
test_Accuracy      0.658      0.653   0.878
train_Precision    0.645      0.426   0.766
test_Precision     0.662      0.426   0.771
train_Recall       0.657      0.652   0.875
test_Recall        0.658      0.653   0.878
train_F1_Score     0.531      0.515   0.817
test_F1_Score      0.532      0.515   0.821
train_Cohen_Kappa  0.017      0.000   0.000
test_Cohen_Kappa   0.020      0.000   0.000

# **LogisticRegression**

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = LogisticRegression(
    max_iter=1000,
    solver='liblinear',
    class_weight='balanced',
    random_state=42,
    C=1.0,
    tol=1e-4     )

est.fit(X_train,y_train)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,est.predict(X_train))),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,est.predict(X_test))),
    'train_Precision': "%.3f"%(precision_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,est.predict(X_train), average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,est.predict(X_test), average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,est.predict(X_train))),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,est.predict(X_test))),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.657      0.652   0.875
test_Accuracy      0.658      0.652   0.878
train_Precision    0.637      0.475   0.811
test_Precision     0.646      0.481   0.815
train_Recall       0.657      0.652   0.875
test_Recall        0.658      0.652   0.878
train_F1_Score     0.534      0.516   0.818
test_F1_Score      0.535      0.516   0.822
train_Cohen_Kappa  0.020      0.001   0.002
test_Cohen_Kappa   0.023      0.001   0.002

# **LinearDiscriminantAnalysis**

In [ ]:
#@title Haciendo una única partición de 80% Train - 20% Test

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = LinearDiscriminantAnalysis(
    solver='lsqr',
    shrinkage='auto',
    n_components=1,
    priors='uniform',
    random_state=42
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.662      0.650   0.880
test_Accuracy      0.660      0.650   0.882
train_Precision    0.631      0.589   0.850
test_Precision     0.625      0.588   0.850
train_Recall       0.662      0.650   0.880
test_Recall        0.660      0.650   0.882
train_F1_Score     0.578      0.536   0.852
test_F1_Score      0.574      0.535   0.853
train_Cohen_Kappa  0.077      0.052   0.243
test_Cohen_Kappa   0.071      0.052   0.227

# **Kneighbors Classifier**

In [ ]:
#@title KNN 1

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = KNeighborsClassifier(
    n_neighbors=10,
    weights='uniform',
    metric='minkowski',
    n_jobs=-1   )

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

                  blinks eyes_state yawning
train_Accuracy     0.850      0.797   0.964
test_Accuracy      0.810      0.750   0.958
train_Precision    0.851      0.784   0.963
test_Precision     0.808      0.720   0.956
train_Recall       0.850      0.797   0.964
test_Recall        0.810      0.750   0.958
train_F1_Score     0.845      0.773   0.962
test_F1_Score      0.803      0.718   0.956
train_Cohen_Kappa  0.650      0.567   0.827
test_Cohen_Kappa   0.556      0.462   0.792

In [ ]:
#@title KNN 2

X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.2, random_state=21)

est = KNeighborsClassifier(
    n_neighbors=10,
    weights='distance',
    leaf_size = 50,
    n_jobs=-1   )

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(X, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.984      0.984   0.997
test_Accuracy      0.847      0.795   0.968
train_Precision    0.984      0.984   0.997
test_Precision     0.845      0.779   0.967
train_Recall       0.984      0.984   0.997
test_Recall        0.847      0.795   0.968
train_F1_Score     0.984      0.984   0.997
test_F1_Score      0.844      0.780   0.967
train_Cohen_Kappa  0.964      0.969   0.985
test_Cohen_Kappa   0.652      0.580   0.846

# **Deep Learning**

In [ ]:
#@title Deep Learning 1

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
import pandas as pd
import numpy as np

# Features y targets
#X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
targets = {
    'blinks': df['blinks'],
    'eyes_state': df['eyes_state'],
    'yawning': df['yawning']
}

# Función mejorada para construir el modelo
def construir_modelo(n_classes):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dropout(0.4))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(512, activation='relu'))

    if n_classes == 2:
        model.add(Dense(1, activation='sigmoid'))
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    else:
        model.add(Dense(n_classes, activation='softmax'))
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

# Métricas
metricas = {}

# Loop por target
for nombre, y in targets.items():
    n_classes = y.nunique()

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

    est = KerasClassifier(
        model=lambda: construir_modelo(n_classes),
        epochs=40,             # Más épocas
        batch_size=64,         # Tamaño de batch aumentado
        verbose=0
    )

    est.fit(X_train, y_train)

    y_pred_train = est.predict(X_train)
    y_pred_test = est.predict(X_test)

    metricas[nombre] = {
        'train_Accuracy': "%.3f"%(accuracy_score(y_train, y_pred_train)),
        'test_Accuracy': "%.3f"%(accuracy_score(y_test, y_pred_test)),
        'train_Precision': "%.3f"%(precision_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Precision': "%.3f"%(precision_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Recall': "%.3f"%(recall_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Recall': "%.3f"%(recall_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_F1_Score': "%.3f"%(f1_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_F1_Score': "%.3f"%(f1_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train, y_pred_train)),
        'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test, y_pred_test)),
    }

# Mostrar resultados
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

                  blinks eyes_state yawning
train_Accuracy     0.655      0.652   0.875
test_Accuracy      0.655      0.653   0.878
train_Precision    0.429      0.426   0.766
test_Precision     0.429      0.426   0.771
train_Recall       0.655      0.652   0.875
test_Recall        0.655      0.653   0.878
train_F1_Score     0.518      0.515   0.817
test_F1_Score      0.518      0.515   0.821
train_Cohen_Kappa  0.000      0.000   0.000
test_Cohen_Kappa   0.000      0.000   0.000

# 4. **Más allá: Buscando Relaciones para mejorar el Modelo.**

In [ ]:
#@title Generación de Cuaterniones

import numpy as np
import pandas as pd
import itertools



# Generar todas las combinaciones únicas de pares (sin repetidos ni espejo)
pairs = list(itertools.combinations(landmarks_importantes, 2))  # (i, j) con i < j

# Función para convertir un vector en un cuaternión con respecto a ref = eje Z
def vector_to_quaternion(v, ref=np.array([0, 0, 1])):
    v = v / np.linalg.norm(v) if np.linalg.norm(v) != 0 else v
    ref = ref / np.linalg.norm(ref)

    axis = np.cross(ref, v)
    axis_norm = np.linalg.norm(axis)

    if axis_norm == 0:
        return np.array([1.0, 0.0, 0.0, 0.0]) if np.dot(ref, v) > 0 else np.array([0.0, 1.0, 0.0, 0.0])

    axis = axis / axis_norm
    angle = np.arccos(np.clip(np.dot(ref, v), -1.0, 1.0))

    w = np.cos(angle / 2.0)
    x, y, z = axis * np.sin(angle / 2.0)
    return np.array([w, x, y, z])

# Calcular cuaterniones para cada fila del dataframe
quaterniones = []

for index, row in df.iterrows():
    fila_q = []
    for i, j in pairs:
        A = np.array([row[f'lmk_{i}_x'], row[f'lmk_{i}_y'], row[f'lmk_{i}_z']])
        B = np.array([row[f'lmk_{j}_x'], row[f'lmk_{j}_y'], row[f'lmk_{j}_z']])
        v = B - A
        q = vector_to_quaternion(v)
        fila_q.extend(q)
    quaterniones.append(fila_q)

del df
gc.collect()

# Convertir a DataFrame de cuaterniones
quat_cols = [f'q_{i}_{j}_{comp}' for i, j in pairs for comp in ['w', 'x', 'y', 'z']]
df_quat = pd.DataFrame(quaterniones, columns=quat_cols)

In [ ]:
#@title Guardar nuevo dataset

output_path = '/content/drive/MyDrive/df_quat.csv'

# 3. Guardar el DataFrame como CSV
df_quat.to_csv(output_path, index=False)

In [ ]:
#@title Cargar el Dataset de Cuaterniones

import pandas as pd
from google.colab import drive
import numpy as np

# Montar Google Drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/df_quat.csv"

df_quat = pd.read_csv(path)
df_quat.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,q_244_172_w,q_244_172_x,q_244_172_y,q_244_172_z,q_244_132_w,q_244_132_x,q_244_132_y,q_244_132_z,q_244_345_w,q_244_345_x,...,q_235_399_y,q_235_399_z,q_235_162_w,q_235_162_x,q_235_162_y,q_235_162_z,q_399_162_w,q_399_162_x,q_399_162_y,q_399_162_z
0,0.721222,-0.668778,-0.180484,0.0,0.787442,-0.550210,-0.277856,0.0,0.808772,-0.231873,...,0.293494,-0.0,0.912422,0.270278,-0.307303,0.0,0.887815,0.036942,-0.458715,0.0
1,0.729671,-0.660884,-0.175534,0.0,0.797167,-0.538971,-0.272094,0.0,0.806755,-0.213752,...,0.294665,-0.0,0.912926,0.268515,-0.307353,0.0,0.890147,0.031900,-0.454555,0.0
2,0.781539,-0.601728,-0.164680,0.0,0.854076,-0.458746,-0.245165,0.0,0.773949,-0.201291,...,0.310359,-0.0,0.893846,0.379810,-0.238293,0.0,0.908013,0.168231,-0.383681,0.0
3,0.742008,-0.641010,-0.196294,0.0,0.809406,-0.511815,-0.287937,0.0,0.797294,-0.253066,...,0.320019,-0.0,0.901193,0.329204,-0.281915,0.0,0.891423,0.114322,-0.438515,0.0
4,0.741444,-0.641624,-0.196416,0.0,0.808570,-0.512172,-0.289644,0.0,0.798961,-0.257317,...,0.315750,-0.0,0.898804,0.334501,-0.283304,0.0,0.889690,0.119595,-0.440622,0.0

In [ ]:
df_quat.shape

(92491, 760)

In [ ]:
#@title KNN Cuaterniones

y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(df_quat, y1, test_size=0.2, random_state=21)

est = KNeighborsClassifier(
    n_neighbors=10,
    weights='distance',
    leaf_size = 50,
    n_jobs=-1   )

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_quat, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_quat, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.975      0.975   0.996
test_Accuracy      0.790      0.744   0.946
train_Precision    0.976      0.976   0.996
test_Precision     0.785      0.719   0.943
train_Recall       0.975      0.975   0.996
test_Recall        0.790      0.744   0.946
train_F1_Score     0.975      0.975   0.996
test_F1_Score      0.783      0.716   0.943
train_Cohen_Kappa  0.944      0.952   0.980
test_Cohen_Kappa   0.512      0.446   0.730

In [ ]:
#@title Random Forest Cuaterniones


X_train, X_test, y_train, y_test = train_test_split(df_quat, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier()

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_quat, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_quat, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                  blinks eyes_state yawning
train_Accuracy     0.975      0.975   0.996
test_Accuracy      0.809      0.758   0.945
train_Precision    0.976      0.976   0.996
test_Precision     0.811      0.754   0.945
train_Recall       0.975      0.975   0.996
test_Recall        0.809      0.758   0.945
train_F1_Score     0.975      0.975   0.996
test_F1_Score      0.799      0.719   0.939
train_Cohen_Kappa  0.944      0.952   0.980
test_Cohen_Kappa   0.545      0.440   0.696

In [ ]:
#@title Deep Learning Cuaterniones

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
import pandas as pd
import numpy as np

# Features y targets
#X = df.drop(["yawning", "indice_video", 'blinks', 'eyes_state'], axis=1)
targets = {
    'blinks': df['blinks'],
    'eyes_state': df['eyes_state'],
    'yawning': df['yawning']
}

# Función mejorada para construir el modelo
def construir_modelo(n_classes):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(df_quat.shape[1],)))
    model.add(Dropout(0.4))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(512, activation='relu'))

    if n_classes == 2:
        model.add(Dense(1, activation='sigmoid'))
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    else:
        model.add(Dense(n_classes, activation='softmax'))
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

# Métricas
metricas = {}

# Loop por target
for nombre, y in targets.items():
    n_classes = y.nunique()

    X_train, X_test, y_train, y_test = train_test_split(df_quat, y, test_size=0.2, random_state=21)

    est = KerasClassifier(
        model=lambda: construir_modelo(n_classes),
        epochs=40,             # Más épocas
        batch_size=64,         # Tamaño de batch aumentado
        verbose=0
    )

    est.fit(X_train, y_train)

    y_pred_train = est.predict(X_train)
    y_pred_test = est.predict(X_test)

    metricas[nombre] = {
        'train_Accuracy': "%.3f"%(accuracy_score(y_train, y_pred_train)),
        'test_Accuracy': "%.3f"%(accuracy_score(y_test, y_pred_test)),
        'train_Precision': "%.3f"%(precision_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Precision': "%.3f"%(precision_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Recall': "%.3f"%(recall_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_Recall': "%.3f"%(recall_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_F1_Score': "%.3f"%(f1_score(y_train, y_pred_train, average='weighted', zero_division=0)),
        'test_F1_Score': "%.3f"%(f1_score(y_test, y_pred_test, average='weighted', zero_division=0)),
        'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train, y_pred_train)),
        'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test, y_pred_test)),
    }

# Mostrar resultados
df_metricas = pd.DataFrame(metricas)
display(df_metricas)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

                  blinks eyes_state yawning
train_Accuracy     0.655      0.652   0.875
test_Accuracy      0.655      0.653   0.878
train_Precision    0.429      0.426   0.766
test_Precision     0.429      0.426   0.771
train_Recall       0.655      0.652   0.875
test_Recall        0.655      0.653   0.878
train_F1_Score     0.518      0.515   0.817
test_F1_Score      0.518      0.515   0.821
train_Cohen_Kappa  0.000      0.000   0.000
test_Cohen_Kappa   0.000      0.000   0.000

In [ ]:
#@title Generando Vectores de Diferencias

import numpy as np
import pandas as pd
import itertools
import gc

# Generar todas las combinaciones únicas de pares (sin repetidos ni espejo)
pairs = list(itertools.combinations(landmarks_importantes, 2))  # (i, j) con i < j

# Calcular vectores normalizados para cada fila del dataframe
vectores = []

for index, row in df.iterrows():
    fila_vec = []
    for i, j in pairs:
        A = np.array([row[f'lmk_{i}_x'], row[f'lmk_{i}_y'], row[f'lmk_{i}_z']])
        B = np.array([row[f'lmk_{j}_x'], row[f'lmk_{j}_y'], row[f'lmk_{j}_z']])
        v = B - A
        norm = np.linalg.norm(v)
        v_normalizado = v / norm if norm != 0 else np.zeros(3)
        fila_vec.extend(v_normalizado)
    vectores.append(fila_vec)

del df
gc.collect()

# Crear columnas para los vectores normalizados
vec_cols = [f'nvec_{i}_{j}_{comp}' for i, j in pairs for comp in ['x', 'y', 'z']]
df_vectores = pd.DataFrame(vectores, columns=vec_cols)

In [ ]:
df_vectores

,nvec_47_52_x,nvec_47_52_y,nvec_47_52_z,nvec_47_58_x,nvec_47_58_y,nvec_47_58_z,nvec_47_97_x,nvec_47_97_y,nvec_47_97_z,nvec_47_101_x,...,nvec_365_457_z,nvec_399_428_x,nvec_399_428_y,nvec_399_428_z,nvec_399_457_x,nvec_399_457_y,nvec_399_457_z,nvec_428_457_x,nvec_428_457_y,nvec_428_457_z
0,-0.334680,-0.929504,0.154958,-0.361035,0.902279,0.235684,0.314309,0.857318,-0.407696,-0.671162,...,-0.324934,0.078102,0.986126,-0.146478,0.094122,0.837459,-0.538335,-0.070387,-0.997318,0.020054
1,-0.347081,-0.926654,0.144389,-0.355432,0.895559,0.267659,0.326044,0.858299,-0.396255,-0.652357,...,-0.344269,0.079504,0.989621,-0.119704,0.081392,0.838886,-0.538188,-0.075955,-0.997073,-0.008785
2,-0.318708,-0.943523,0.090498,-0.342847,0.823359,0.452257,0.226213,0.930726,-0.287361,-0.707781,...,-0.420032,0.046274,0.998586,-0.026156,0.010848,0.929658,-0.368264,-0.058492,-0.992495,-0.107384
3,-0.299892,-0.945884,0.123971,-0.387206,0.871006,0.302356,0.257245,0.899889,-0.352172,-0.738171,...,-0.345192,0.033928,0.993594,-0.107791,0.034343,0.886343,-0.461753,-0.032739,-0.999338,-0.015848
4,-0.297407,-0.947054,0.120988,-0.389575,0.870628,0.300395,0.258066,0.901777,-0.346698,-0.732396,...,-0.346513,0.032812,0.994254,-0.101891,0.034223,0.886850,-0.460789,-0.031318,-0.999279,-0.021468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92486,-0.385010,-0.921100,0.057810,-0.314067,0.806933,0.500221,0.260626,0.924017,-0.279761,-0.687598,...,-0.511689,0.090658,0.995666,0.020729,0.049742,0.927038,-0.371654,-0.102336,-0.980519,-0.167660
92487,-0.391924,-0.917746,0.064321,-0.312465,0.812388,0.492333,0.272371,0.917279,-0.290540,-0.686449,...,-0.517274,0.095680,0.995294,0.015365,0.058743,0.920719,-0.385780,-0.105347,-0.980875,-0.163667
92488,-0.395177,-0.916851,0.056734,-0.314931,0.802891,0.506147,0.276293,0.917317,-0.286691,-0.686352,...,-0.533027,0.092397,0.995497,0.021183,0.059551,0.921608,-0.383527,-0.100655,-0.980094,-0.171126
92489,-0.393768,-0.917531,0.055537,-0.317551,0.798811,0.510943,0.275515,0.918091,-0.284957,-0.689097,...,-0.537946,0.090905,0.995585,0.023363,0.058706,0.921985,-0.382749,-0.098991,-0.979692,-0.174368
92490,-0.394315,-0.916862,0.062294,-0.311929,0.800126,0.512346,0.275049,0.916248,-0.291270,-0.686457,...,-0.541621,0.095027,0.995310,0.018096,0.057178,0.920960,-0.385439,-0.105252,-0.979605,-0.171161

In [ ]:
#@title Guardar Dataset Vectores Diferencia

output_path = '/content/drive/MyDrive/df_diff.csv'

# 3. Guardar el DataFrame como CSV
df_vectores.to_csv(output_path, index=False)

In [ ]:
#@title Cargar el Dataset de Vectores Diferencia

import pandas as pd
from google.colab import drive
import numpy as np

# Montar Google Drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/df_diff.csv'

df_diff = pd.read_csv(path)
df_diff.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,nvec_47_52_x,nvec_47_52_y,nvec_47_52_z,nvec_47_58_x,nvec_47_58_y,nvec_47_58_z,nvec_47_97_x,nvec_47_97_y,nvec_47_97_z,nvec_47_101_x,...,nvec_365_457_z,nvec_399_428_x,nvec_399_428_y,nvec_399_428_z,nvec_399_457_x,nvec_399_457_y,nvec_399_457_z,nvec_428_457_x,nvec_428_457_y,nvec_428_457_z
0,-0.334680,-0.929504,0.154958,-0.361035,0.902279,0.235684,0.314309,0.857318,-0.407696,-0.671162,...,-0.324934,0.078102,0.986126,-0.146478,0.094122,0.837459,-0.538335,-0.070387,-0.997318,0.020054
1,-0.347081,-0.926654,0.144389,-0.355432,0.895559,0.267659,0.326044,0.858299,-0.396255,-0.652357,...,-0.344269,0.079504,0.989621,-0.119704,0.081392,0.838886,-0.538188,-0.075955,-0.997073,-0.008785
2,-0.318708,-0.943523,0.090498,-0.342847,0.823359,0.452257,0.226213,0.930726,-0.287361,-0.707781,...,-0.420032,0.046274,0.998586,-0.026156,0.010848,0.929658,-0.368264,-0.058492,-0.992495,-0.107384
3,-0.299892,-0.945884,0.123971,-0.387206,0.871006,0.302356,0.257245,0.899889,-0.352172,-0.738171,...,-0.345192,0.033928,0.993594,-0.107791,0.034343,0.886343,-0.461753,-0.032739,-0.999338,-0.015848
4,-0.297407,-0.947054,0.120988,-0.389575,0.870628,0.300395,0.258066,0.901777,-0.346698,-0.732396,...,-0.346513,0.032812,0.994254,-0.101891,0.034223,0.886850,-0.460789,-0.031318,-0.999279,-0.021468

In [ ]:
#@title Random Forest Vectores Diferencia

y1 = df['blinks']
y2 = df['eyes_state']
y3 = df['yawning']

X_train, X_test, y_train, y_test = train_test_split(df_diff, y1, test_size=0.2, random_state=21)

est = RandomForestClassifier(
    n_estimators=200
)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas = {}

metricas['blinks'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_diff, y2, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['eyes_state'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

X_train, X_test, y_train, y_test = train_test_split(df_diff, y3, test_size=0.2, random_state=21)

est.fit(X_train,y_train)
y_pred_train = est.predict(X_train)
y_pred_test = est.predict(X_test)

metricas['yawning'] = {
    'train_Accuracy': "%.3f"%(accuracy_score(y_train,y_pred_train)),
    'test_Accuracy': "%.3f"%(accuracy_score(y_test,y_pred_test)),
    'train_Precision': "%.3f"%(precision_score(y_train,y_pred_train, average= 'weighted')),
    'test_Precision': "%.3f"%(precision_score(y_test,y_pred_test, average= 'weighted')),
    'train_Recall': "%.3f"%(recall_score(y_train,y_pred_train, average= 'weighted')),
    'test_Recall': "%.3f"%(recall_score(y_test,y_pred_test, average= 'weighted')),
    'train_F1_Score': "%.3f"%(f1_score(y_train,y_pred_train, average= 'weighted')),
    'test_F1_Score': "%.3f"%(f1_score(y_test,y_pred_test, average= 'weighted')),
    'train_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_train,y_pred_train)),
    'test_Cohen_Kappa': "%.3f"%(cohen_kappa_score(y_test,y_pred_test)),
}

# Convertir a DataFrame
df_metricas = pd.DataFrame(metricas)

# Mostrar tabla
display(df_metricas)

NameError: name 'df' is not defined

In [ ]:
df_diff.shape

(92491, 570)